In [2]:
import numpy as np 

## numpy array

In [5]:
benimListem = [20,30,40]

In [7]:
type(benimListem)

list

In [9]:
type(np.array(benimListem))

numpy.ndarray

In [11]:
np.array(benimListem)

array([20, 30, 40])

In [13]:
matrixListesi = [[10,20,30],[20,30,50],[70,80,50]]

In [15]:
matrixListesi[2][0]

70

In [17]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 50],
       [70, 80, 50]])

## arange

In [22]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

## zeros

In [33]:
np.zeros(5) # 0 oluşturuyor

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [39]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [41]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [46]:
np.linspace(0,20,5) # 0 ile 20 arasında 5 elemanlı olcak ve eşit aralıklı olucak şekilde dizi oluşturuyır

array([ 0.,  5., 10., 15., 20.])

In [48]:
np.linspace(0,30,20) # 0 ve 30 arasındaki rakamları 20 elemanlı olacak şekilde eşit aralıklara böldü

array([ 0.        ,  1.57894737,  3.15789474,  4.73684211,  6.31578947,
        7.89473684,  9.47368421, 11.05263158, 12.63157895, 14.21052632,
       15.78947368, 17.36842105, 18.94736842, 20.52631579, 22.10526316,
       23.68421053, 25.26315789, 26.84210526, 28.42105263, 30.        ])

## eye

In [53]:
np.eye(10) #sadece  köşegen 1 gerisi 0 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [60]:
np.random.randn()

-0.6582673438256613

In [62]:
np.random.randn(4)

array([ 0.5612611 ,  0.10349307, -2.03511746, -0.12860109])

In [66]:
np.random.randn(5,5)

array([[ 0.57032188, -0.03853971,  0.13042469, -1.11632229, -0.58274557],
       [ 0.02337773, -0.41354756,  0.14157741,  1.08262078, -1.04647706],
       [ 0.36803259,  0.86985163,  0.55240725,  0.19216109,  0.27361832],
       [-2.67815234,  0.78900223,  0.23556429, -0.99131301,  0.96049335],
       [-1.35499638, -0.96174999,  1.06607788,  2.31169725,  0.28930462]])

In [74]:
np.random.randint(1,10) #verilen aralıkta sadece 1 değer döndürür ve int stop dahil değil (10)

6

In [76]:
np.random.randint(1,30,5) #1 ve 30 arasında 5 adet rakam veriyor

array([24, 12, 25, 18, 22])

## bir değişkene eşitleme

In [92]:
benimNumpyDizim = np.arange(30)

In [94]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [96]:
benimRandomDizim = np.random.randint(0,100,20)

In [98]:
benimRandomDizim

array([41, 23, 53, 55, 90, 21, 80, 93, 15, 22, 32,  2, 30, 71, 54, 58, 62,
       57, 32, 43])

## numpy dizi methodları

In [102]:
benimNumpyDizim.reshape(5,5)

ValueError: cannot reshape array of size 30 into shape (5,5)

In [104]:
benimNumpyDizim.reshape(5,6) # çünkü dizimde 30 tane rakam var (row,column) (6'şar ayırdı)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [106]:
benimRandomDizim.max()

93

In [108]:
benimRandomDizim.min()

2

In [112]:
benimRandomDizim.argmax() #Max elemanın indexini verir

7

In [114]:
benimRandomDizim.argmin() #Min elemanın indexini verir

11

In [118]:
benimNumpyDizim.shape 

(30,)

In [126]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [120]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [122]:
reshapeDizim.shape

(5, 6)

In [124]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [130]:
reshapeDizim[0][0]

0

In [132]:
reshapeDizim[1][5] #(satır,sutün)

11