In [2]:
import numpy as np 

In [4]:
benimDizim = np.arange(0,15)

In [6]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
benimDizim[5]

5

In [17]:
benimDizim[3:8] #listelerdeki gibi çalışıyor

array([3, 4, 5, 6, 7])

In [19]:
benimDizim[3:8] = -5

In [21]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [23]:
baskaDizi = np.arange(0,24)

In [25]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
baskaDizi[4:9]

array([4, 5, 6, 7, 8])

In [39]:
slicingDizisi = baskaDizi[4:9]

In [41]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [33]:
slicingDizisi = 700

In [35]:
slicingDizisi # bu direk int olan 700 e eşitleniyor ve type da int 

700

In [49]:
slicingDizisi[:] = 700  #doğru kullanım bu şekildedir

In [51]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [53]:
baskaDizi  ##buradaki rakamlarda değişti ben şok 

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## orijinali değiştirmeden yapmak için 

In [56]:
ornekDizi = np.arange(0,24)

In [58]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
ornekDiziKopyası = ornekDizi.copy()

In [62]:
ornekDiziKopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [64]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [66]:
ornekDiziKopyaSlicing = ornekDiziKopyası[3:6]

In [68]:
ornekDiziKopyaSlicing[:] = 800

In [70]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [72]:
ornekDiziKopyası

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [74]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

 ## eğer orijinal dizinin bozulmasını istemiyor isen orijinal dizinin bir kopyasını üret ve onun üzerinden işlem yap 

#### Bu işlemler pek vektörel oldu çünkü tek boyutlu , 2 boyutlu (matrix) de nasıl işlem yapılır ??

# Matrix

In [93]:
benimListem = [[10,20,30],[40,50,60],[70,80,90]]

In [95]:
matrixDizim = np.array(benimListem)

In [97]:
matrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [99]:
matrixDizim[0]

array([10, 20, 30])

In [101]:
matrixDizim[0][2]

30

In [103]:
matrixDizim[1,2]

60

In [113]:
matrixDizim[1:,2]  # 1. indexten başla ve onların 2. indexlerini getir

array([60, 90])

In [127]:
matrixDizim[1:,0:] #1. indexten başla ve onların 0. indexinden son indexine kadar getir

array([[40, 50, 60],
       [70, 80, 90]])

In [129]:
matrixDizim[2:,0:2] #1. indexten başla ve onların 0. indexinden 2. indexine kadar getir (2 dahil değil)

array([[70, 80]])

## [a:b:e,c:d:e] 
#### gibi düşün, a ve b satır başlangıç ve bitiş , c ve d sutün başlangıç ve bitiş (bitişler dahil değil ) e de atlama sayısı

In [139]:
yenimatrix = np.arange(0,60)

In [143]:
yenimatrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [145]:
shapematrix = yenimatrix.reshape(6,10)

In [147]:
shapematrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [149]:
shapematrix [2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [153]:
shapematrix[[5,2]] # liste gibi yazınca istediğim indexleri veriyor

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [157]:
shapematrix[1:5:2,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [161]:
shapematrix[:5,1:10:2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

# operasyonlar

In [208]:
yenibirdizi = np.random.randint(1,100,20)

In [210]:
yenibirdizi

array([65, 51, 92, 89, 22, 82, 44, 86, 71, 40, 18, 38, 49, 38, 10, 50, 58,
        7, 47, 63])

In [212]:
yenibirdizi > 50

array([ True,  True,  True,  True, False,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True, False,
       False,  True])

In [214]:
sonucdizisi = yenibirdizi > 50

In [216]:
yenibirdizi

array([65, 51, 92, 89, 22, 82, 44, 86, 71, 40, 18, 38, 49, 38, 10, 50, 58,
        7, 47, 63])

In [218]:
sonucdizisi

array([ True,  True,  True,  True, False,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True, False,
       False,  True])

In [220]:
yenibirdizi[sonucdizisi] # sadece true değerleri alır

array([65, 51, 92, 89, 82, 86, 71, 58, 63])

In [222]:
yenibirdizi

array([65, 51, 92, 89, 22, 82, 44, 86, 71, 40, 18, 38, 49, 38, 10, 50, 58,
        7, 47, 63])

In [224]:
yenibirdizi[yenibirdizi>50] # bu kod ile aynı filtreyi elde edebiliriz

array([65, 51, 92, 89, 82, 86, 71, 58, 63])

In [226]:
sondizi = np.arange(0,5)

In [228]:
sondizi

array([0, 1, 2, 3, 4])

In [230]:
sondizi + sondizi # indexler toplanıyor

array([0, 2, 4, 6, 8])

In [238]:
sondizi - sondizi # indexler toplanıyor

array([0, 0, 0, 0, 0])

In [236]:
sondizi * sondizi # indexler toplanıyor

array([ 0,  1,  4,  9, 16])

In [232]:
sondizi # orijinali değişmiyor

array([0, 1, 2, 3, 4])

In [234]:
sondizi + baskaDizi # aynı boyutlarda olmalıdır

ValueError: operands could not be broadcast together with shapes (5,) (24,) 

In [242]:
np.sqrt(sondizi) #karekök alıyor

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [244]:
np.max(sondizi)

4